/*
 * @Author: LYM
 * @Date: 2022-05-26 13:48:08
 * @LastEditors: LYM
 * @LastEditTime: 2022-06-01 09:07:56
 * @Description: Please set Description
 */
// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {}
export {}
