// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CockpitIconList: typeof import('./src/components/cockpit-manage/cockpit-icon-list.vue')['default']
    CockpitIconlistItem: typeof import('./src/components/cockpit-manage/cockpit-iconlist-item.vue')['default']
    CockpitIconListItem: typeof import('./src/components/cockpit-manage/cockpit-icon-list-item.vue')['default']
    CockpitList: typeof import('./src/components/cockpit-manage/cockpit-list.vue')['default']
    CockpitListItem: typeof import('./src/components/cockpit-manage/cockpit-list-item.vue')['default']
    CockpitListTools: typeof import('./src/components/cockpit-manage/cockpit-list-tools.vue')['default']
    CockpitTool: typeof import('./src/components/cockpit-manage/cockpit-tool.vue')['default']
    CreateCockpit: typeof import('./src/components/cockpit-manage/modal/create-cockpit.vue')['default']
    CreateFolder: typeof import('./src/components/cockpit-manage/modal/create-folder.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Rename: typeof import('./src/components/cockpit-manage/modal/rename.vue')['default']
    RenameFolderCockpit: typeof import('./src/components/cockpit-manage/modal/rename-folder-cockpit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
